server:
  port: 8083
spring:
  application:
    name: gbss-pong
  mvc:  #springBoot版本太高，缺少swagger运行环境,增加配置兼容
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  instance:
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url: #EurekaServer 地址
      defaultZone: http://localhost:8085/eureka
